-- =============================================================================
-- CIVIX Platform — Migration 009: Workflow, Forensics & Legal
-- Phase 2A Physical DDL Implementation
-- Date: 2026-08-29
-- Authority: docs/03_DATABASE_SCHEMA_BIBLE.md §Migration 11, 12, 13
--            BLK-01/ADR-012: lead_priority_enum, lead_status_enum, task_type_enum, task_status_enum
-- =============================================================================

SET search_path TO civix, public;

-- ---------------------------------------------------------------------------
-- civix.investigative_lead
-- Generated by AI or investigator. AI CANNOT auto-confirm.
-- ---------------------------------------------------------------------------
CREATE TABLE civix.investigative_lead (
    lead_id              UUID                      PRIMARY KEY DEFAULT gen_random_uuid(),
    case_id              UUID                      NOT NULL REFERENCES civix.investigative_case(case_id),
    generated_by_run_id  UUID                      NULL REFERENCES civix.analysis_run(run_id),
    generated_by_person  UUID                      NULL REFERENCES civix.civix_user(user_id),
    lead_text            TEXT                      NOT NULL,
    explanation          TEXT                      NULL,
    priority             civix.lead_priority_enum  NOT NULL DEFAULT 'MEDIUM',
    status               civix.lead_status_enum    NOT NULL DEFAULT 'OPEN',
    ai_confidence        DECIMAL(5,4)              NULL CHECK (ai_confidence BETWEEN 0.0 AND 1.0),
    created_at           TIMESTAMPTZ               NOT NULL DEFAULT now(),
    disposition_notes    TEXT                      NULL,
    disposed_by          UUID                      NULL REFERENCES civix.civix_user(user_id),
    disposed_at          TIMESTAMPTZ               NULL,

    CONSTRAINT chk_lead_has_origin
        CHECK (generated_by_run_id IS NOT NULL OR generated_by_person IS NOT NULL)
);

-- ---------------------------------------------------------------------------
-- civix.investigation_task
-- Action item derived from a lead or created directly on a case.
-- ---------------------------------------------------------------------------
CREATE TABLE civix.investigation_task (
    task_id        UUID                     PRIMARY KEY DEFAULT gen_random_uuid(),
    lead_id        UUID                     NULL REFERENCES civix.investigative_lead(lead_id),
    case_id        UUID                     NOT NULL REFERENCES civix.investigative_case(case_id),
    task_type      civix.task_type_enum     NOT NULL,
    assigned_to    UUID                     NULL REFERENCES civix.civix_user(user_id),
    status         civix.task_status_enum   NOT NULL DEFAULT 'PENDING',
    due_date       DATE                     NULL,
    outcome_notes  TEXT                     NULL,
    created_at     TIMESTAMPTZ              NOT NULL DEFAULT now(),
    completed_at   TIMESTAMPTZ              NULL

    -- task_status = 'COMPLETED' should correlate with completed_at IS NOT NULL
    -- Enforced at application layer
);

-- ---------------------------------------------------------------------------
-- Forensic Stubs (MVP — Phase 2 extensibility)
-- Full forensic model (20 tables) architectured but not implemented in MVP.
-- Authority: Schema Bible §Migration 12
-- ---------------------------------------------------------------------------

CREATE TABLE civix.forensic_report (
    report_id       UUID    PRIMARY KEY DEFAULT gen_random_uuid(),
    instance_id     UUID    NOT NULL REFERENCES civix.evidence_instance(instance_id),
    report_type     TEXT    NOT NULL,
    lab_name        TEXT    NULL,
    examiner_name   TEXT    NULL,
    findings_summary TEXT   NULL
);

CREATE TABLE civix.medical_report (
    report_id         UUID    PRIMARY KEY DEFAULT gen_random_uuid(),
    instance_id       UUID    NOT NULL REFERENCES civix.evidence_instance(instance_id),
    examination_type  TEXT    NOT NULL,
    findings_summary  TEXT    NULL,
    practitioner_name TEXT    NULL,
    examination_date  DATE    NULL
);

-- DEFERRED: forensic_sample, chain_of_custody_event, lab_examination, lab_result,
--           reference_profile, comparison, forensic_finding, medical_examination,
--           medical_finding, autopsy, toxicology_result
-- (Phase 2 full forensic expansion)

-- ---------------------------------------------------------------------------
-- civix.legal_restriction
-- Documents legal restrictions on entities or artifacts.
-- Legal restriction ≠ physical deletion (INV-12).
-- ---------------------------------------------------------------------------
CREATE TABLE civix.legal_restriction (
    restriction_id       UUID                            PRIMARY KEY DEFAULT gen_random_uuid(),
    target_entity_id     UUID                            NULL REFERENCES civix.entity(entity_id),
    target_artifact_id   UUID                            NULL REFERENCES civix.evidence_artifact(artifact_id),
    restriction_type     civix.legal_restriction_type_enum NOT NULL,
    authority            TEXT                            NOT NULL,  -- Court, law, agency
    court_order_reference TEXT                           NULL,
    effective_range      TSTZRANGE                       NOT NULL,  -- When the restriction is in effect
    scope                TEXT                            NOT NULL,  -- What is restricted
    status               TEXT                            NOT NULL DEFAULT 'ACTIVE',
    -- Values: ACTIVE, LIFTED, EXPIRED
    created_by           UUID                            NOT NULL REFERENCES civix.civix_user(user_id),
    lifted_by            UUID                            NULL REFERENCES civix.civix_user(user_id),
    lifted_at            TIMESTAMPTZ                     NULL,

    CONSTRAINT chk_restriction_has_target
        CHECK (target_entity_id IS NOT NULL OR target_artifact_id IS NOT NULL)
);
-- INV-12: Legal restriction does NOT physically delete data.
-- RLS must handle restricted entity/artifact visibility.

-- ---------------------------------------------------------------------------
-- civix.audit_event
-- Append-only audit trail. NEVER UPDATE or DELETE.
-- INV-13 enforced by trigger in migration 010.
-- ---------------------------------------------------------------------------
CREATE TABLE civix.audit_event (
    audit_id         UUID                    PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id          UUID                    NOT NULL REFERENCES civix.civix_user(user_id),
    action           civix.audit_action_enum NOT NULL,
    target_table     TEXT                    NOT NULL,
    target_id        UUID                    NOT NULL,
    case_context_id  UUID                    NULL REFERENCES civix.investigative_case(case_id),
    ip_address       INET                    NULL,
    timestamp        TIMESTAMPTZ             NOT NULL DEFAULT now(),
    metadata         JSONB                   NULL
);
-- INVARIANT (INV-13): Append-only. BEFORE UPDATE OR DELETE trigger raises exception.
-- Trigger defined in migration 010.

-- ---------------------------------------------------------------------------
-- civix.outbox — Transactional Outbox for Neo4j CDC
-- Authority: ADR-008, INV-20
-- This is the ONLY mechanism for Neo4j synchronization.
-- ---------------------------------------------------------------------------
CREATE TABLE civix.outbox (
    id          UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    entity_id   UUID        NOT NULL,    -- ID of the PostgreSQL row being synced
    action      TEXT        NOT NULL,    -- UPSERT_NODE, UPSERT_EDGE, DEACTIVATE_NODE,
                                         -- DEACTIVATE_EDGE, TOMBSTONE_NODE, TOMBSTONE_EDGE
    entity_type TEXT        NOT NULL,    -- Table name or logical entity type
    payload     JSONB       NOT NULL,    -- Full payload for Neo4j merge
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    consumed_at TIMESTAMPTZ NULL         -- Set by CDC consumer; NULL = pending
);
-- INV-20: No direct Neo4j write is allowed in application code.
-- ONLY the CDC consumer (future Phase 7) reads from this table.

COMMENT ON TABLE civix.outbox IS
    'Transactional outbox for Neo4j CDC. ONLY mechanism for Neo4j sync. No direct Neo4j writes allowed. ADR-008, INV-20.';
