-- =============================================================================
-- CIVIX Platform — Migration 035: Investigator Assertion Lifecycle
-- Phase: Graph Workspace Backend Remediation
-- Date: 2026-09-06
-- Authority: Graph Workspace Architectural Remediation (ADR-REM-01 through ADR-REM-05)
--
-- PURPOSE:
--   Extends civix.assertion to support investigator-proposed relationships.
--   Investigators can propose relationships (S-P-O) using existing predicate_enum
--   values, with a separate lifecycle (PROPOSED → ACCEPTED/REJECTED) that prevents
--   proposals from becoming authoritative facts without supervisor review.
--
-- DESIGN DECISIONS:
--   ADR-REM-01: Reuses existing predicate_enum — no generic catch-all predicate.
--   ADR-REM-02: PROPOSED assertions are NOT projected to Neo4j.
--   ADR-REM-03: Only ACCEPTED_BY_SUPERVISOR assertions are projected.
--
-- INVARIANTS PRESERVED:
--   INV-01: Stance still lives in hypothesis_support, not assertion.
--   INV-08: AI cannot autonomously confirm a hypothesis (unrelated, preserved).
--   INV-18: No free-text predicates — proposal uses existing predicate_enum.
--   BLK-15/ADR-017: authorized_case_ids[] remains enforced.
--
-- SAFETY:
--   IDEMPOTENT: Uses IF NOT EXISTS / DO NOTHING patterns where supported.
--   Existing AI/system-generated assertions remain unchanged.
--   Hero/Golden data is unaffected (existing rows get safe defaults).
--   No historical assertions are rewritten.
-- =============================================================================

SET search_path TO civix, public;

-- ---------------------------------------------------------------------------
-- 1. New ENUM: assertion_origin_enum
--    Discriminates the epistemic source of an assertion.
--    AI_PIPELINE: generated by the C3 intelligence engine or automated analysis.
--    SYSTEM_DERIVED: generated by ingestion/ETL without direct AI inference.
--    INVESTIGATOR_PROPOSED: authored by a human investigator, pending review.
-- ---------------------------------------------------------------------------
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'assertion_origin_enum' AND typnamespace = (SELECT oid FROM pg_namespace WHERE nspname = 'civix')) THEN
        CREATE TYPE civix.assertion_origin_enum AS ENUM (
            'AI_PIPELINE',
            'SYSTEM_DERIVED',
            'INVESTIGATOR_PROPOSED'
        );
    END IF;
END$$;

COMMENT ON TYPE civix.assertion_origin_enum IS
    'Epistemic origin of an assertion. INVESTIGATOR_PROPOSED requires proposal_status lifecycle. AI_PIPELINE and SYSTEM_DERIVED default to NOT_APPLICABLE proposal_status. ADR-REM-01.';

-- ---------------------------------------------------------------------------
-- 2. New ENUM: proposal_status_enum
--    Tracks the review lifecycle of an INVESTIGATOR_PROPOSED assertion.
--    NOT_APPLICABLE: for AI_PIPELINE / SYSTEM_DERIVED assertions (default).
--    PROPOSED: investigator has submitted, awaiting supervisor review.
--    ACCEPTED_BY_SUPERVISOR: supervisor has approved — authoritative.
--    REJECTED: supervisor has rejected — not projected to graph.
-- ---------------------------------------------------------------------------
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'proposal_status_enum' AND typnamespace = (SELECT oid FROM pg_namespace WHERE nspname = 'civix')) THEN
        CREATE TYPE civix.proposal_status_enum AS ENUM (
            'NOT_APPLICABLE',
            'PROPOSED',
            'ACCEPTED_BY_SUPERVISOR',
            'REJECTED'
        );
    END IF;
END$$;

COMMENT ON TYPE civix.proposal_status_enum IS
    'Review lifecycle for INVESTIGATOR_PROPOSED assertions. AI/system assertions use NOT_APPLICABLE. Supervisor review is mandatory for PROPOSED → ACCEPTED transition. ADR-REM-02.';

-- ---------------------------------------------------------------------------
-- 3. Extend civix.assertion with proposal lifecycle columns
-- ---------------------------------------------------------------------------

-- 3a. assertion_origin — discriminates epistemic source
ALTER TABLE civix.assertion
    ADD COLUMN IF NOT EXISTS assertion_origin civix.assertion_origin_enum
        NOT NULL DEFAULT 'AI_PIPELINE';

COMMENT ON COLUMN civix.assertion.assertion_origin IS
    'Epistemic origin. AI_PIPELINE = C3 engine. SYSTEM_DERIVED = ingestion. INVESTIGATOR_PROPOSED = human proposal pending review.';

-- 3b. proposal_status — review lifecycle (only meaningful when origin = INVESTIGATOR_PROPOSED)
ALTER TABLE civix.assertion
    ADD COLUMN IF NOT EXISTS proposal_status civix.proposal_status_enum
        NOT NULL DEFAULT 'NOT_APPLICABLE';

COMMENT ON COLUMN civix.assertion.proposal_status IS
    'Review lifecycle status. Must be NOT_APPLICABLE for AI_PIPELINE and SYSTEM_DERIVED assertions. ADR-REM-02.';

-- 3c. investigator_justification — mandatory human-readable rationale for INVESTIGATOR_PROPOSED
ALTER TABLE civix.assertion
    ADD COLUMN IF NOT EXISTS investigator_justification TEXT NULL;

COMMENT ON COLUMN civix.assertion.investigator_justification IS
    'Mandatory justification text when assertion_origin = INVESTIGATOR_PROPOSED. NULL for AI/system assertions.';

-- 3d. reviewed_by — supervisor who approved/rejected the proposal
ALTER TABLE civix.assertion
    ADD COLUMN IF NOT EXISTS reviewed_by UUID NULL
        REFERENCES civix.civix_user(user_id);

COMMENT ON COLUMN civix.assertion.reviewed_by IS
    'The supervisor/admin who reviewed the investigator proposal. NULL while PROPOSED or for non-investigator assertions.';

-- 3e. reviewed_at — timestamp of review decision
ALTER TABLE civix.assertion
    ADD COLUMN IF NOT EXISTS reviewed_at TIMESTAMPTZ NULL;

COMMENT ON COLUMN civix.assertion.reviewed_at IS
    'Timestamp of supervisor review decision. NULL while PROPOSED or for non-investigator assertions.';

-- ---------------------------------------------------------------------------
-- 4. Database-level CHECK constraints
--    Enforces cross-column consistency. Cannot be bypassed from application layer.
-- ---------------------------------------------------------------------------

-- 4a. Non-investigator assertions must have NOT_APPLICABLE proposal_status
ALTER TABLE civix.assertion
    ADD CONSTRAINT chk_assertion_origin_status_consistency
    CHECK (
        (assertion_origin = 'INVESTIGATOR_PROPOSED')
        OR
        (assertion_origin IN ('AI_PIPELINE', 'SYSTEM_DERIVED') AND proposal_status = 'NOT_APPLICABLE')
    );

COMMENT ON CONSTRAINT chk_assertion_origin_status_consistency ON civix.assertion IS
    'AI_PIPELINE and SYSTEM_DERIVED assertions must have proposal_status = NOT_APPLICABLE. ADR-REM-01.';

-- 4b. Investigator proposals require a justification text
ALTER TABLE civix.assertion
    ADD CONSTRAINT chk_investigator_justification_required
    CHECK (
        assertion_origin != 'INVESTIGATOR_PROPOSED'
        OR (assertion_origin = 'INVESTIGATOR_PROPOSED' AND investigator_justification IS NOT NULL AND length(trim(investigator_justification)) > 0)
    );

COMMENT ON CONSTRAINT chk_investigator_justification_required ON civix.assertion IS
    'INVESTIGATOR_PROPOSED assertions must supply a non-empty justification text. ADR-REM-01.';

-- 4c. Review fields (reviewed_by, reviewed_at) must be consistent
ALTER TABLE civix.assertion
    ADD CONSTRAINT chk_assertion_review_fields_consistent
    CHECK (
        (reviewed_by IS NULL AND reviewed_at IS NULL)
        OR (reviewed_by IS NOT NULL AND reviewed_at IS NOT NULL)
    );

COMMENT ON CONSTRAINT chk_assertion_review_fields_consistent ON civix.assertion IS
    'reviewed_by and reviewed_at must both be set or both be NULL. Cannot record a review without both reviewer identity and timestamp.';

-- 4d. Accepted/Rejected proposals must have a reviewer
ALTER TABLE civix.assertion
    ADD CONSTRAINT chk_assertion_review_required_for_terminal_states
    CHECK (
        proposal_status NOT IN ('ACCEPTED_BY_SUPERVISOR', 'REJECTED')
        OR (proposal_status IN ('ACCEPTED_BY_SUPERVISOR', 'REJECTED') AND reviewed_by IS NOT NULL AND reviewed_at IS NOT NULL)
    );

COMMENT ON CONSTRAINT chk_assertion_review_required_for_terminal_states ON civix.assertion IS
    'ACCEPTED_BY_SUPERVISOR and REJECTED assertions must have a reviewer. No anonymous silent acceptance.';

-- ---------------------------------------------------------------------------
-- 5. Add SUPERVISOR_REVIEW to audit_action_enum
--    So review decisions are properly tracked in the audit trail.
-- ---------------------------------------------------------------------------
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_enum e
        JOIN pg_type t ON t.oid = e.enumtypid
        WHERE t.typname = 'audit_action_enum'
          AND t.typnamespace = (SELECT oid FROM pg_namespace WHERE nspname = 'civix')
          AND e.enumlabel = 'SUPERVISOR_REVIEW'
    ) THEN
        ALTER TYPE civix.audit_action_enum ADD VALUE 'SUPERVISOR_REVIEW';
    END IF;
END$$;

-- ---------------------------------------------------------------------------
-- 6. Update assertion outbox trigger to include proposal lifecycle fields
--    The existing trigger fires on: INSERT OR UPDATE OF predicate, epistemic_status,
--    authorized_case_ids, subject_entity_id, object_entity_id, tx_end
--    We update the trigger FUNCTION to include new fields in payload.
--    We also extend the trigger to fire on proposal_status changes.
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION civix.trg_upsert_epistemic_and_edge_outbox()
RETURNS TRIGGER LANGUAGE plpgsql SECURITY INVOKER AS $$
DECLARE
    v_entity_type TEXT;
    v_entity_id UUID;
    v_payload JSONB;
    v_target_type civix.entity_type_enum;
BEGIN
    IF TG_TABLE_NAME = 'event' THEN
        v_entity_id := NEW.event_id;
        v_entity_type := 'event';
        v_payload := jsonb_build_object(
            'event_id', NEW.event_id,
            'event_type', NEW.event_type,
            'occurred_at_lower', lower(NEW.occurred_at),
            'occurred_at_upper', upper(NEW.occurred_at),
            'description', NEW.description
        );

    ELSIF TG_TABLE_NAME = 'assertion' THEN
        v_entity_id := NEW.assertion_id;
        v_entity_type := 'assertion';
        
        -- Resolve the object_entity_type dynamically without violating normalization
        SELECT entity_type INTO v_target_type FROM civix.entity WHERE entity_id = NEW.object_entity_id;
        
        v_payload := jsonb_build_object(
            'assertion_id', NEW.assertion_id,
            'predicate', NEW.predicate,
            'epistemic_status', NEW.epistemic_status,
            'authorized_case_ids', NEW.authorized_case_ids,
            'subject_entity_id', NEW.subject_entity_id,
            'object_entity_id', NEW.object_entity_id,
            'object_entity_type', v_target_type,
            'tx_end', NEW.tx_end,
            -- Proposal lifecycle fields (new in migration 035)
            'assertion_origin', NEW.assertion_origin,
            'proposal_status', NEW.proposal_status,
            'investigator_justification', NEW.investigator_justification,
            'reviewed_by', NEW.reviewed_by,
            'reviewed_at', NEW.reviewed_at
        );

    ELSIF TG_TABLE_NAME = 'hypothesis' THEN
        v_entity_id := NEW.hypothesis_id;
        v_entity_type := 'hypothesis';
        v_payload := jsonb_build_object(
            'hypothesis_id', NEW.hypothesis_id,
            'case_id', NEW.case_id,
            'hypothesis_text', NEW.hypothesis_text,
            'status', NEW.status,
            'tx_end', NEW.tx_end
        );

    ELSIF TG_TABLE_NAME = 'investigative_lead' THEN
        v_entity_id := NEW.lead_id;
        v_entity_type := 'investigative_lead';
        v_payload := jsonb_build_object(
            'lead_id', NEW.lead_id,
            'case_id', NEW.case_id,
            'lead_text', NEW.lead_text,
            'priority', NEW.priority,
            'status', NEW.status
        );

    ELSIF TG_TABLE_NAME = 'event_participant' THEN
        v_entity_id := NEW.participant_id;
        v_entity_type := 'event_participant';
        
        SELECT entity_type INTO v_target_type FROM civix.entity WHERE entity_id = NEW.entity_id;

        v_payload := jsonb_build_object(
            'participant_id', NEW.participant_id,
            'event_id', NEW.event_id,
            'entity_id', NEW.entity_id,
            'entity_type', v_target_type,
            'participant_role', NEW.participant_role,
            'role_confidence', NEW.role_confidence
        );

    ELSIF TG_TABLE_NAME = 'hypothesis_support' THEN
        v_entity_id := NEW.support_id;
        v_entity_type := 'hypothesis_support';
        v_payload := jsonb_build_object(
            'support_id', NEW.support_id,
            'hypothesis_id', NEW.hypothesis_id,
            'assertion_id', NEW.assertion_id,
            'stance', NEW.stance,
            'weight', NEW.weight,
            'tx_end', NEW.tx_end
        );

    ELSIF TG_TABLE_NAME = 'identity_resolution' THEN
        v_entity_id := NEW.resolution_id;
        v_entity_type := 'identity_resolution';
        v_payload := jsonb_build_object(
            'resolution_id', NEW.resolution_id,
            'source_identity_id', NEW.source_identity_id,
            'resolved_person_id', NEW.resolved_person_id,
            'status', NEW.status,
            'superseded_by', NEW.superseded_by,
            'tx_end', NEW.tx_end
        );
    END IF;

    IF v_payload IS NOT NULL THEN
        INSERT INTO civix.outbox (entity_id, action, entity_type, payload)
        VALUES (v_entity_id, 'UPSERT_NODE', v_entity_type, v_payload);
    END IF;

    RETURN NEW;
END;
$$;

-- Extend the assertion outbox trigger to also fire on proposal_status changes.
-- (The existing trigger column list did not include proposal_status.)
DROP TRIGGER IF EXISTS trg_assertion_upsert_outbox ON civix.assertion;

CREATE TRIGGER trg_assertion_upsert_outbox 
AFTER INSERT OR UPDATE OF predicate, epistemic_status, authorized_case_ids, subject_entity_id, object_entity_id, tx_end, proposal_status, reviewed_by ON civix.assertion 
FOR EACH ROW EXECUTE FUNCTION civix.trg_upsert_epistemic_and_edge_outbox();

COMMENT ON TRIGGER trg_assertion_upsert_outbox ON civix.assertion IS
    'Migration 035: Extended to fire on proposal_status and reviewed_by changes so supervisor approvals are propagated through the CDC → Neo4j pipeline.';

-- ---------------------------------------------------------------------------
-- 7. Index for fast lookup of pending proposals by case
-- ---------------------------------------------------------------------------
CREATE INDEX IF NOT EXISTS idx_assertion_proposal_status
    ON civix.assertion (proposal_status)
    WHERE proposal_status IN ('PROPOSED', 'ACCEPTED_BY_SUPERVISOR', 'REJECTED');

COMMENT ON INDEX civix.idx_assertion_proposal_status IS
    'Fast lookup of investigator proposals by lifecycle state. Migration 035.';

CREATE INDEX IF NOT EXISTS idx_assertion_origin
    ON civix.assertion (assertion_origin);

COMMENT ON INDEX civix.idx_assertion_origin IS
    'Fast discrimination between AI/system and investigator-proposed assertions. Migration 035.';

-- ---------------------------------------------------------------------------
-- 8. Validation
-- ---------------------------------------------------------------------------
DO $$
DECLARE
    v_col_count INT;
    v_inv18_violations INT;
BEGIN
    -- Verify all 5 new columns exist
    SELECT COUNT(*) INTO v_col_count
    FROM information_schema.columns
    WHERE table_schema = 'civix' AND table_name = 'assertion'
      AND column_name IN ('assertion_origin', 'proposal_status', 'investigator_justification', 'reviewed_by', 'reviewed_at');
    
    IF v_col_count != 5 THEN
        RAISE EXCEPTION 'Migration 035 validation failed: expected 5 new columns on civix.assertion, found %', v_col_count;
    END IF;
    
    -- Verify existing AI assertions are unaffected (they should all default to AI_PIPELINE/NOT_APPLICABLE)
    -- INV-18 check: all assertions must still have enum predicates
    SELECT COUNT(*) INTO v_inv18_violations
    FROM civix.assertion
    WHERE predicate IS NULL;
    
    IF v_inv18_violations > 0 THEN
        RAISE EXCEPTION 'Migration 035 validation failed: % assertions have NULL predicate (INV-18 violation)', v_inv18_violations;
    END IF;
    
    RAISE NOTICE 'Migration 035 validation passed: % new columns verified, INV-18 intact.', v_col_count;
END$$;

-- =============================================================================
-- END Migration 035
-- =============================================================================
