@echo off
echo Reconfiguring postgresql-x64-17 service path...
sc.exe config postgresql-x64-17 binPath= "\"C:\Program Files\PostgreSQL\17\bin\pg_ctl.exe\" runservice -N \"postgresql-x64-17\" -D \"D:\PostgreSQL\17\data\" -w"
echo Starting postgresql-x64-17 service...
net start postgresql-x64-17
